### ISSUE TITLE
Switch to Bootstrap v5

### ISSUE THREAD

**Issue by WKHAllen** [WKHAllen/LutherNavigator#43]
Upgrade to Bootstrap version 5.x.x. Test all pages to ensure no problems have arisen.

**Comment by WKHAllen** [comment]
**Note**: in `<select>` elements, the class `"form-control"` must be changed to `"form-select"`.

**Comment by himlne01** [comment]
> **Note**: in `<select>` elements, the class `"form-control"` must be changed to `"form-select"`.

Is this still relevant? Otherwise I will close this issue.

**Comment by WKHAllen** [comment]
> > **Note**: in `<select>` elements, the class `"form-control"` must be changed to `"form-select"`.
> 
> Is this still relevant? Otherwise I will close this issue.

Yes, this is still relevant. The class Bootstrap 5 uses is "form-select" and not "form-control", which Bootstrap 4 uses for select elements.
