### ISSUE TITLE
Stars on posts are too small

### ISSUE THREAD

**Issue by oniani** [WKHAllen/LutherNavigator#62]
Stars on the post are not very readable.
We could use font awesome or just use a different (larger) font for stars.
Alternatively, we could have a horizontal bar with 5 mini-bars. The number of "filled" bars would then specify the rating.

**Comment by WKHAllen** [comment]
The plan is to improve this in the near future, using one of the methods you mentioned.

**Comment by WKHAllen** [comment]
This has been fixed. We are using star icons via font awesome.
